### ISSUE TITLE
Koinos CDT Binary Installation

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-sdk-cpp#17]
As a smart contract developer, I want to quickly download and begin using the Koinos CDT.

- [x] Write script that tars the CDT from a temporary installation directory. (Lives in CDT) #228
- [x] Write script that downloads and untars CDT binary to permanent installation directory. (Temporarily lives in CDT) #229
- [x] Document set up process to build a smart contract for Koinos. (Should be Readme) #230
