### ISSUE TITLE
Contract Development Toolkit

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-sdk-cpp#35]
As a Koinos smart contract developer, I would like to use a CMake project with a `CMAKE_TOOLCHAIN_FILE` to build my smart contracts.

- [x] Research a way to distribute a `CMAKE_TOOLCHAIN_FILE` that contains dynamic paths (http://github.com/ruslo/polly) (#36)
- [x] Build `koinos-wasi-sdk` locally for both macOS and Linux and publish a release `.tar.gz` for usage within CI in `koinos-cdt` (koinos/koinos-wasi-sdk#1)
- [x] Modify `koinos-cdt` to not submodule `koinos-wasi-sdk` and utilize `CMAKE_TOOLCHAIN_FILE` to discover the location of `koinos-wasi-sdk` (#37)
- [x] Create a Travis CI build script that pulls binaries from `koinos-wasi-sdk` releases, uses the said files to set variable in `koinos-cdt` and build the result in CI (#38)
- [x] Modify `koinos-types` to accept a CMake flag `EXCEPTIONS_ENABLED` that will allow for CDT to use it without exceptions. Where we used to throw we should assert. (koinos/koinos-types#200)
- [x] Create a repository (Koinos business logic) of smart contracts utilizing the `CMAKE_TOOLCHAIN_FILE` and ensure that it works with Koinos (koinos/koinos-internal#47)
