### ISSUE TITLE
Implement Koinos CDT with necessary components 

### ISSUE THREAD

**Issue by brklyn8900** [koinos/koinos-sdk-cpp#7]
As a smart contract developer, I want to easily build the Koinos smart contract development kit. 

 - [x] Top level build script that builds our custom clang wasm compiler (#6).
 - [x] Write cmake toolchain file for Koinos system (#8).
 - [x] Install compiler and cmake toolchains to standard system location (#9).
